// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = module.exports;

  config['Tests'] = {
    environment: 'node',
    rootPath: '../',
    sources: [],
    tests: ['spec/*-test.js']
  };

}).call(this);
