// Generated by CoffeeScript 1.6.3
(function() {
  var buster, cli, execSync, _;

  buster = require('buster');

  _ = require('underscore');

  execSync = require('exec-sync');

  cli = require('../bin/cli');

  buster.testCase('It enforces proper arguments', {
    '--> Single invalid command exits error': function() {
      return buster.assert.same('test', 'test');
    },
    '--> Multiple commands fail': function() {
      return buster.assert.same('test', 'test');
    },
    '//--> Single valid command exits success': function() {}
  });

}).call(this);
